apiVersion: v1
kind: Service
metadata:
  name: drupal-mariadb
  labels:
    app: drupal
spec:
  ports:
    - port: 3306
  selector:
    app: drupal
    tier: mariadb
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: drupal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: drupal-mariadb
  labels:
    app: drupal
spec:
  selector:
    matchLabels:
      app: drupal
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: mariadb
    spec:
      containers:
      - image: mariadb:10.2
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: HorriblePassword
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
